### ISSUE TITLE
Analysis project

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#116]
Develop project (similar in nature to the `analyze_o2` project) to perform analysis of timeslides and the injection events. 

Considering we are dealing with much shorter background time (~10,000 seconds compared to an entire observing run ), I think we should use one single background `Distribution` for all the injection events. This background distribution will just be the accumulation of all the timeslides we performed.

For each injection event, we want a FAR as a function of latency from trigger time. From there we can create the time dependent ROC curves (see #5)

**Comment by EthanMarx** [comment]
I now noticing the use of the `make_shift` `Segment` method to utilize all the timeslide data nearest to the 'event'. 

For this to work, segments will need to be produced as follows:
1. Query science segments for both Ifos
2. Find the interesection
3. perform circular time sliding on a _per segment_ basis

(One thing to be aware of is that if a `Segment` is less than `n_slides * dt` in length, some of the slides will be the same. )

I'm trying to remember why I was initially against this approach. I think I thought it would be difficult to reconstruct the times of the timeshifted data, but I am realizing that the TimeSlide and Segment objects make this easy. Overall, I think it will be much easier to change the timeslide code than to restructure the analysis code, so I think we should revert back to this version of performing timeslides.

**Comment by EthanMarx** [comment]
Yeah that makes the most sense to me, although I don't think it's a problem to include _all_ the background timeslides, including the timeslide corresponding to the injection segment. The background events are guaranteed background due to the timeshift.  This will save us from having to rebuild backgrounds each time.

**Comment by alecgunny** [comment]
One thing that just occurred to me is that we probably don't want to use the 0 shift background segments for building the background distribution, because we'll want to use those to fit a normalizer for the injection segments, rather than the injection segments themselves since those will of course contain events that will throw off the normalization. This way we can analyze each event as if it popped up out of clear blue background rather than a few seconds after another event (or several events)

**Comment by EthanMarx** [comment]
Yeah that's a good point. It might be a bit complicated since we probably want to normalize each injection segment on the raw background segment associated with the timeslide it was injected into. Maybe the `integrate` function can take an `Optional` `normalizer_segment`, which, if passed, can be used to normalize the `segment`. Otherwise, the `segment` itself is used.

**Comment by EthanMarx** [comment]
Agreed. There are a few functions in the `injection` library (e.g `inject_signal_into_timeslides`) I have similar thoughts about.
