### ISSUE TITLE
Allow Distributions ability to incorporate vetoes

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#128]
Allow the `Distribution` class the ability to take a list of veto segments and disregard background events that lie in these segments. I'm not sure what the best way to implement this is. For example, the `Cluster` distribution class assumes contiguous times, so removing times would, at the moment, be problematic. One basic approach would be to set the network outputs for all vetoed times to `-inf` in the `Distributions` `.fit` method.

**Comment by alecgunny** [comment]
Would it be sufficient to handle this in the parent class's `.fit` method by breaking a `Segment` up if necessary into multiple sub-segments, then running `.update` on each one of these new, shorter segments?
