### ISSUE TITLE
Interactive data visualization app

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#142]
Given initial plots from the first full pipeline run, build an interactive data visualization application via Bokeh serve which can load data source data and provide some insights into model performance. Initial ideas include:
- Scatter plot of event SNR vs. network output for both background and signal events. Use a selector to choose NN output normalization period (pre-computed, likely handle via JS callback rather than server callback). Clicking on a point will load both its spectrograms from both ifos, as well as a line plot of the NN output over that same window.
- Possibly include a lasso tool that allows the user to select a region of data from the scatter plot, then plot where in (Hanford) time each point lies, with the y-axis showing the time shift for each point.
- TPR vs. SNR plots, with a slider for choosing the target FPR in units of $\text{yrs}^{-1}$. Will probably need to compute all of these up front

**Comment by EthanMarx** [comment]
Additionally, compute sensitive distances as function of FAR (outlined [here](https://dcc.ligo.org/DocDB/0183/P2200233/001/MLGWSC_1_v2.pdf)(

**Comment by EthanMarx** [comment]
Another useful component could be a toggle for vetoes, that will remove vetoed events in the scatter plot, recalculate ROC curves/ Figures of merit, etc.

**Comment by alecgunny** [comment]
Resolved with #165
