### ISSUE TITLE
Don't run CI workflow on draft pull requests

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#145]
Is it worth setting up our workflows so that they don't run on draft PRs, that way we aren't wasting cycles on code we know won't work? Should be as simple as adding `if: github.event.pull_request.draft == false` to the `ci-tests` job in `.github/workflows/ci-tests.yaml`, but just wanted to open up the discussion to confirm this would be desirable first?

**Comment by deepchatterjeeligo** [comment]
Is there a limit on the runner, or the number of pulls that are allowed? We could follow an honor code that folks will add something like a `[skip-ci]` in gitlab to the commit message if the intention is just to save progress, or share will others, instead of actually testing.
