### ISSUE TITLE
Timeslide memory issue

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#152]
Ran into the memory issue outlined [here](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/timeslide_injections/timeslide_injections.py#L378L382) on a segment of length ~ 30,000 seconds. One solution off the top of my head would be to add a `max_segement_length` argument that ensures we won't run out of memory, and if we have segments larger than this, split them up.

**Comment by EthanMarx** [comment]
One drawback of this method is these longer segments become discontiguous

**Comment by alecgunny** [comment]
Closed by #189
