### ISSUE TITLE
Remove stride argument from BBHInMemoryDataset initialization in train.py

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/BBHNet#160]
The `BBHInMemoryDataset` class was modified to remove `stride` as an argument, but the argument was not removed from [here](https://github.com/ML4GW/BBHNet/blob/08b06862286b9217af7a012c86e6ccf9fffb8950/projects/sandbox/train/train/train.py#L222) in train.py. The line should be deleted.

**Comment by EthanMarx** [comment]
Will take care of this and #157 in #150
