### ISSUE TITLE
Saving injection parameters bug in timeslide injection project

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#166]
The timeslide injection project [currently overwrites](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/timeslide_injections/timeslide_injections.py#L413#L415) injection parameters when saving parameters from a new segment within the same timeslide.  

Can either save a new file for each segment, or append. (I think appending probably makes things easier for analysis). 

PR addressing this should check for this in tests.

**Comment by alecgunny** [comment]
I'll need to address this in #165 since this absence of these parameters is making it impossible to make some of the plots we've discussed
