### ISSUE TITLE
`return` statements cause issue with `conda`

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/BBHNet#173]
`return` statements in the functions specified in the `pyproject.toml` halt the pipeline due to an interaction with `conda`. Removing this statements is fine for some projects, but not others. A `return` value is necessary for the tests to run in `generate_waveforms` and `wrapper.py` expects a `return` value from `train`.

**Comment by alecgunny** [comment]
@wbenoit26 this was closed with #171 yeah?

**Comment by wbenoit26** [comment]
Yup
