### ISSUE TITLE
Forced generation of glitches raises error

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/BBHNet#174]
Running `generate_glitches` with `force_generation = true` creates an error because the glitch file is opened in append mode and the file contains a dataset with the same name. Easiest solution is probably to generate all glitches before saving so that the file can be opened in write mode.

**Comment by EthanMarx** [comment]
Nice catch, would maybe moving the `with` (in write mode) to before the `for ifo` loop in `main` solve it?

**Comment by wbenoit26** [comment]
Yeah, that works. I'll wrap that into my PR

**Comment by alecgunny** [comment]
@wbenoit26 this was solved with #171 yeah?

**Comment by wbenoit26** [comment]
Yup
