### ISSUE TITLE
Longer kernels break training

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/BBHNet#230]
When running `train` with a kernel length between (2.5, 4] , the project breaks unexpectedly.

It also fails for times longer than 4 seconds, but I believe this is expected, due to the length of the glitches saved during the glitch generation step.

It would be best to fix at least the first issue.

**Comment by EthanMarx** [comment]
Can you provide some more details on the bug?

**Comment by wbenoit26** [comment]
Sure, I've been trying to figure out the root cause, but I haven't been able to get very far. Here's (part of) the output when the kernel length is 3:

```
/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/gwpy/timeseries/timeseries.py:938: UserWarning: resample() rate matches current sample_rate (2048.0 Hz), returning input data unmodified; please double-check your parameters
  warnings.warn(
/home/william.benoit/ML4GW/BBHNet/libs/data/bbhnet/data/transforms/transform.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  value = torch.tensor(value, dtype=dtype)
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [96,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [97,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [126,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [127,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [30,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [780,0,0], thread: [31,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [960,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [960,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [960,0,0], thread: [42,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [960,0,0], thread: [43,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [575,0,0], thread: [120,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [575,0,0], thread: [121,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [575,0,0], thread: [127,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [959,0,0], thread: [96,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [959,0,0], thread: [127,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [959,0,0], thread: [64,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [959,0,0], thread: [95,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/bin/train", line 6, in <module>
    sys.exit(main())
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/hermes/typeo/typeo.py", line 572, in wrapper
    result = subcommand(**subkw)
  File "/home/william.benoit/ML4GW/BBHNet/libs/architectures/bbhnet/architectures/wrapper.py", line 26, in arch_fn
    return fn(**fn_kwargs)
  File "/home/william.benoit/ML4GW/BBHNet/libs/trainer/bbhnet/trainer/trainer.py", line 141, in train
    X, y = next(iter(train_dataset))
  File "/home/william.benoit/ML4GW/BBHNet/libs/data/bbhnet/data/dataloader.py", line 72, in __next__
    X, y = self.preprocessor(X, y)
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/william.benoit/ML4GW/BBHNet/projects/sandbox/train/train/utils.py", line 26, in forward
    inputs = module(*inputs)
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/william.benoit/ML4GW/BBHNet/libs/data/bbhnet/data/waveform_injection.py", line 11, in forward
    X, idx, _ = super().forward(X)
  File "/home/william.benoit/ML4GW/BBHNet/ml4gw/ml4gw/transforms/injection.py", line 438, in forward
    waveforms, sampled_params = self.sample(N)
  File "/home/william.benoit/ML4GW/BBHNet/ml4gw/ml4gw/transforms/injection.py", line 391, in sample
    ifo_responses = gw.compute_observed_strain(
  File "/home/william.benoit/ML4GW/BBHNet/ml4gw/ml4gw/gw.py", line 244, in compute_observed_strain
    antenna_responses = compute_antenna_responses(
  File "/home/william.benoit/ML4GW/BBHNet/ml4gw/ml4gw/gw.py", line 142, in compute_antenna_responses
    return torch.einsum("...jk,ijk->...i", polarization, detector_tensors)
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

The error is different each time, though. All of the `../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator():` errors have different numbers, and there's a different amount of them.

**Comment by wbenoit26** [comment]
This is coming from [here](https://github.com/ML4GW/ml4gw/blob/ce861a1645b6c52fbadebf46b03f8ce634981355/ml4gw/utils/slicing.py#L252) in slicing.py. The wrong combination of `center`, `max_center_offset`, and `kernel_size` can yield indices less than 0.

**Comment by wbenoit26** [comment]
Yeah, I agree that this is desirable behavior (other than the lack of error message) for what we're dealing with. I'm thinking about how I might want to circumvent it for BNS mergers, where I'll want kernels longer than 2.5 seconds. The limiting factor is just that we get glitches in 4 second segments, so I might start by not training specifically on glitches.

**Comment by alecgunny** [comment]
You could just sample longer glitch stretches right?

I think I'm confused because this looks like it's happening during waveform sampling, so it seems like it's a limitation of the length of the waveform dataset you've generated. How long are the waveforms (in s)? What's the particular combination of `kernel_size` and `max_center_offset` that's generating this error?

**Comment by EthanMarx** [comment]
The amount of data that we query around glitch times is defined by the `window` parameter (see [here](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/pyproject.toml#L53) in the config) which can easily be changed. Note that this is actually a "half" window. So for a window of 2 seconds, we query 2 seconds to the right and left of glitch times determined by omicron. As Alec mentioned this might not be the direct cause of your problem, but worth noting.

**Comment by wbenoit26** [comment]
@alecgunny No, it happens during glitch sampling, the above traceback is misleading. This is what it shows when I run training with `device = "cpu"`:
```
Traceback (most recent call last):
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/bin/train", line 6, in <module>
    sys.exit(main())
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/hermes/typeo/typeo.py", line 572, in wrapper
    result = subcommand(**subkw)
  File "/home/william.benoit/ML4GW/BBHNet/libs/architectures/bbhnet/architectures/wrapper.py", line 26, in arch_fn
    return fn(**fn_kwargs)
  File "/home/william.benoit/ML4GW/BBHNet/libs/trainer/bbhnet/trainer/trainer.py", line 142, in train
    X, y = next(iter(train_dataset))
  File "/home/william.benoit/ML4GW/BBHNet/libs/data/bbhnet/data/dataloader.py", line 72, in __next__
    X, y = self.preprocessor(X, y)
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/william.benoit/ML4GW/BBHNet/projects/sandbox/train/train/utils.py", line 26, in forward
    inputs = module(*inputs)
  File "/home/william.benoit/.cache/pypoetry/virtualenvs/train-FvzPYKWf-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/william.benoit/ML4GW/BBHNet/libs/data/bbhnet/data/glitch_sampler.py", line 48, in forward
    glitches = sample_kernels(
  File "/home/william.benoit/ML4GW/BBHNet/ml4gw/ml4gw/utils/slicing.py", line 278, in sample_kernels
    return slice_kernels(X, idx, kernel_size)
  File "/home/william.benoit/ML4GW/BBHNet/ml4gw/ml4gw/utils/slicing.py", line 145, in slice_kernels
    return torch.take_along_dim(x, kernels, axis=-1)
RuntimeError: index -879 is out of bounds for dimension 2 with size 8192
```

@EthanMarx Yeah, that's true, I'm just a little worried about windows that are too large. Not sure exactly how long the kernel should be, but it'll likely be about a minute, meaning we'd want a window of a couple minutes for the glitches, if I just scale up the times. I'd worry about about having multiple glitches in one segment, though that's probably not super likely.

**Comment by EthanMarx** [comment]
Couple of things:

1. If there are instances where there are multiple glitches in your window (whatever size it may be), you will definitely want to use those instances during training. Otherwise, your network will never learn to reject them! 
2. I'd be interested to see how well the current BBHnet extrapolates to kernel sizes an order of magnitude longer. I imagine you'd need a much larger network.  
3. It might be worth trying to keep the kernel size similar to what we have now (maybe a couple seconds). We currently enforce that the coalescence time has to lie in the kernel, but you could think about removing this restriction. For a given waveform, you could then sample kernels from the inspiral as well as the merger, labelling them both as signals. I don't think the current `sample_kernels` currently supports this, but I shouldnt be too difficult to modify it.

**Comment by alecgunny** [comment]
Agreed with the points above. I think just from a computation and memory standpoint I can't imagine being able to support minute long kernels, nor do I suspect that the architecture as it stands could capture correlations that long-term: a minute-long receptive field would require an enormous network. There are other architectures that are meant for longer term correlations (e.g. WaveNet) that might be worth exploring for this, but you're still going to be bottlenecked by the memory required for a forward and backward step for inputs of that size.

Would `sample_kernels` not support this? Isn't this what a positive `max_center_offset` is meant to achieve?

**Comment by EthanMarx** [comment]
I initially thought so. I was confused a bit by the following line in the documentation for positive `max_center_offset`
```
the leftmost edge will always be sampled such that the center of
the timeseries falls within the kernel.
```
Which to me implies that the coalescence time (i.e. center of timeseries) is always in the kernel.

**Comment by alecgunny** [comment]
The relevant code is
```python
    elif max_center_offset >= 0:
        min_val = center - max_center_offset - kernel_size
        max_val = center
```

**Comment by EthanMarx** [comment]
Okay great. @wbenoit26 In theory, you could even keep all of the parameters the same, with the exception of the `trigger_distance` (see [here](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/pyproject.toml#L101) in the config). When converted from seconds to number of samples this is equivalent to the `max_center_offset` in the discussion above. This controls how far from the coalescence time you will sample kernels from. For example, a value of 60 would mean you are sampling kernels that begin a minute before coalescence time.

**Comment by wbenoit26** [comment]
For sure, I fully anticipate needing to modify the architecture, among other things, to be able to run with kernels of any significant length. That'll be a future step that I look into.

I'll try out what you're suggesting, Ethan, that sounds like a interesting test.

**Comment by EthanMarx** [comment]
@wbenoit26 This was resolved on the `ml4gw` side correct?

**Comment by wbenoit26** [comment]
Sorry, didn't get a notification about your comment for some reason. You are correct, I'll close this now.
