### ISSUE TITLE
Longer duration waveforms

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/BBHNet#234]
I was running into issues with longer waveforms just because I did my math wrong with how long `buffer` needed to be to allow a longer `waveform_duration`. Still, we should probably have a check in place to make sure all of `shifts`, `num_slides`, `buffer`, `jit`, and `waveform_duration` are compatible.

**Comment by alecgunny** [comment]
Ahh ok got it, yeah agreed that makes sense
