### ISSUE TITLE
VT `vizapp` improvements

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#259]
Some improvements for the VT portion of the vizapp:

- Analogously to the [`gaussian_masses`](https://github.com/ML4GW/BBHNet/blob/main/libs/priors/bbhnet/priors/priors.py#L149), add a `log_normal_masses` distribution. (A nice bonus would be the ability to switch between these distributions as a `widget`)
- Add a `bokeh` `NumericInput` widget for the standard deviation of the distribution.
- Fix [this](https://github.com/ML4GW/BBHNet/blob/main/libs/priors/bbhnet/priors/priors.py#L161) bug where the `m2` mean was set as `m1` that @rafia17 nicely pointed out.
- Remove the time component from the VT. (Maybe make the `livetime` an `Optional` parameter in the `VolumeTimeIntegral`).
- Add the gstlal or pycbc VT's from the catalog paper. I think this might be best as a table next to the VT plot. The rows could be the (m1, m2) pair and the columns individual pipelines. This should also be normalized by the livetime which can be found in the catalog paper as well.

**Comment by EthanMarx** [comment]
Some more things: 

- Add a HoverTool (See [here](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/vizapp/vizapp/plots/background.py#L150) in the background project) so we can see the exact values of the `VT`, `n_eff`, and `uncertainty`.
- Remove the [second y-axis ](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/vizapp/vizapp/plots/vt.py#L52L58) that plots the `n_eff` (doesn't make sense here)

**Comment by wbenoit26** [comment]
Just turning this into a checklist for tracking:

- [x] Analogously to the [`gaussian_masses`](https://github.com/ML4GW/BBHNet/blob/main/libs/priors/bbhnet/priors/priors.py#L149), add a `log_normal_masses` distribution. (A nice bonus would be the ability to switch between these distributions as a `widget`)
- [x] Add a `bokeh` `NumericInput` widget for the standard deviation of the distribution.
- [x] Fix [this](https://github.com/ML4GW/BBHNet/blob/main/libs/priors/bbhnet/priors/priors.py#L161) bug where the `m2` mean was set as `m1` that @rafia17 nicely pointed out.
- [ ] Remove the time component from the VT. (Maybe make the `livetime` an `Optional` parameter in the `VolumeTimeIntegral`).
- [ ] Add the gstlal or pycbc VT's from the catalog paper. I think this might be best as a table next to the VT plot. The rows could be the (m1, m2) pair and the columns individual pipelines. This should also be normalized by the livetime which can be found in the catalog paper as well.
- [x] Add a HoverTool (See [here](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/vizapp/vizapp/plots/background.py#L150) in the background project) so we can see the exact values of the `VT`, `n_eff`, and `uncertainty`.
- [x] Remove the [second y-axis ](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/vizapp/vizapp/plots/vt.py#L52L58)that plots the `n_eff` (doesn't make sense here)
