### ISSUE TITLE
Breaking up O3 data

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#27]
How do we want to break up the first month of O3 data for training/validation/test?

If we adopt the local averaging method outlined in [the analysis slideshow](https://nbviewer.org/github/alecgunny/bbhnet-monorepo/blob/main/projects/o2-timeslide-analysis/overview.slides.html#/), we'll probably want to insert an extra test set before the "proper" test set for optimizing the normalization window length.

We should also consider that we'll eventually want to extend to a re-training pipeline, so it's probably worth picking these and building the code for constructing them such that

1. we have enough data to repeat this procedure across the course of a month
2. there's some logical cadence that can be extended to new segments

**Comment by EthanMarx** [comment]
Linking [wiki](../wikis/BBHnet-Training-Validation-Testing) page created to summarize current status of this issue:
