### ISSUE TITLE
Write inference script as a single run of a particular shift across all segments to parallelize along shift dimension

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#277]

**Comment by EthanMarx** [comment]
I'm looking at the current `infer` project and I don't think much will have to change.
We can simply point the `SequenceManager` directly at a `TimeSlide` directory instead of the `datadir` that contains all of the `TimeSlide` dirs

**Comment by EthanMarx** [comment]
Forgot that we also wan't to be doing injections on the fly, and likely won't be saving any data to disk.
Here's my first go at pseudo code of what this might look like

```python
def infer(
    waveform_path: Path, # path to omnibus waveforms file
    shift: float,
    segments: List[Tuple[float, float]],
    triton_server_ip: str, # already spun up on SDSC or something
    ...
):

    waveforms = load_waveforms(waveform_path)

    client = InferenceClient(triton_server_ip, model_name, model_version)

    # something analogous to the SequenceManager we have now
    sequence_manager = SequenceManager(write_dir, client, ...)

    for segment in segments:
        # load data and timeshift
        background = load_data(segment, channel, ifos)
        background = np.roll(background, shift * sample_rate)

        # add to inference queue
        sequence_manager.add_to_queue(background, field="background")
       
        # slice out waveforms, inject, and add to inference queue
        waveforms = find_waveforms_in_segment(segment, waveforms)
        injected = inject_waveforms(waveforms, background, times)
        sequence_manager.add_to_queue(injected, field="injected")

    events = defaultdict(ClusterDistribution)
    while not sequence_manager.is_done():
        # instead of writing nn outputs to disk, the callback will be clustering events
        future = client.get()
        if future is None:
            time.sleep(1e-2)
            continue

    
        while not future.done():
            sequence_events, field = future.result()
            events[field].append(sequence_events)
```

**Comment by alecgunny** [comment]
I think something like this will make sense, but the point of the `SequenceManager` was really just to make parallelization easier. Since we're parallelizing via Condor now, I think we can drop this and just manage each sequence explicitly in serial. I'll see if I can mock something based off of this up this afternoon.

**Comment by EthanMarx** [comment]
I see. If it doesn't add too much complexity, is it not worth trying to parallelize within each condor job as well?

**Comment by alecgunny** [comment]
It depends on your scale I guess, but probably not. Our throughput at this point is such that a single GPU can almost be saturated with each stream, so you need roughly as many streams as you have GPUs. Adding streams within a client will just make figuring out the load balances more complicated

**Comment by EthanMarx** [comment]
Sounds good. So then in our implementation the optimal setup is one GPU per time slide?

**Comment by alecgunny** [comment]
It's looking that way, though that could also change with a better GPU than the V100. Whatever setup we end up putting together we can do some true benchmarking on it at some point to really optimize our deployment
