### ISSUE TITLE
Generate injection sets up front in `datagen` before inference

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#278]

**Comment by EthanMarx** [comment]
Given #275 I think the best way to do this would be to create a file of injections for each `shift`. This should also take into account hopeless injections specified in #285

**Comment by alecgunny** [comment]
Isn't the plan to only do 0-lag injections on the revamped inference?

I like the idea of taking into account hopeless injections. Do we want to calculate SNR wrt the training PSD, in which case the injection-set generation function will have to accept arguments for getting this data, or just wrt the general O3 PSD which I think gwpy has built-in support for grabbing?

**Comment by EthanMarx** [comment]
I think for now we keep the flexibility to inject into timeslides since we're still working with small amounts of data? Programatically it shouldn't be too difficult to make this a toggle. 

For calculating SNRS I think starting with the training PSD makes sense. 

This project will require a few things that we already query in other datagen projects: 
1. Science segments for determining how many waveforms we need to inject
2. PSDs (which are derived from the background project) for calculating SNRS

My thought was we could add a caching mechanism for these as well. 

My other thought was that this would be contained in the same project that generates the training waveforms. I think this will make it more obvious what each prior represents: When sampling from the `end_o3ratesandpop` prior to generate testing injections we can explicitly show the conversion to detector frame masses.

**Comment by alecgunny** [comment]
Yeah I think consolidating things into simpler waveform generation and handling API will be super useful. I was going to make a simple mock up and then I got super carried away so forgive the complexity of the code in this gist but something like it could be pretty powerful:

https://gist.github.com/alecgunny/ea6124895968fdfc50b0de33828791e3

So to give an idea of how the API might get used, you might do something like:
```python
from bilby.core.prior import PriorDict

intrinsic_prior = PriorDict(mass_1=...)  # just for intrinsic parameters
samples = intrinsic_prior.sample(500)
instrinsic_params = IntrinsicParameterSet(**samples)
waveform_set = IntrinsicWaveformSet.from_parameters(
    instrinsic_params,
    minimum_frequency=20,
    ...
)
```

Alternatively, if you wanted to parallelize the generation, you could do
```python
from concurrent.futures import ThreadPoolExecutor # or ProcessPoolExecutor
with ThreadPoolExecutor(4) as ex:
    waveform_set = IntrinsicWaveformSet.from_parameters(
        instrinsic_params,
        minimum_frequency=20,
        ...,
        ex=ex
    )
```

Then you could do the projection like
```python
extrinsic_prior = PriorDict(...)
segments = [(1234567890, 1234568914), ...]
shifts = [(0, 0), (0, 1), ...]
gps_times, shifts = do_some_kind_of_gross_logic(
    segments, shifts, spacing=40, jitter=1, buffer=4
)
extrinsic_params = extrinsic_prior.sample(len(gps_times))
extrinsic_params.update({"gps_time": gps_times, "shift": shift})
extrinsic_params = ExtrinsicParameterSet(**extrinsic_params)

# if we want to include a torch dependency here, we could
# build this in (we could even make torch optional and do
# the ml4gw load under the function, then catch any ImportError)
responses = InterferometerResponseSet.from_polarizations(waveform_set, extrinsic_params)
# or as an alternative syntax that I haven't yet implemented
waveform_set.project(extrinsic_params)

for start, end in segments:
    background = get_data(start, end)
    for shift in shifts:
        background = do_simple_slice_shift(background)
        injected = responses.slice_segment(start, end, shift).inject(background, start)
```
There would be simple save and load methods (with some options for more bells and whistles with wildcards, see my note in the gist):
```python
waveform_set.to_hdf5("raw-polarizations.h5")
reloaded_waveform_set = InstrinsicWaveformSet.from_hdf5("raw-polarizations.h5")

responses.to_hdf5("projections_H{shift[0]}-L{shift[1]}.h5")
reloaded_responses = InterferometerResponseSet.from_hdf5("how-to-specify-wildcard-load?")

# also load for just a particular segment/shift, if you have multiple in a file
InterferfometerResponseSet.from_hdf5("omnibus-file.hdf5", start=start, end=end, shifts=[(0, 0), (0, 1)])

# or maybe extend to callables for loading so
# that you can use metadata, e.g.
desired_timestamp = 1234567906
def find_specific_waveform_from_timestamp(f): # f is the h5py File object
    idx = np.where(f["parameters"]["gps_time"] == desired_timestamp)[0]
    return idx

InterferometerResponseSet.from_hdf5("...", filter_=find_specific_waveform_from_timestamp)
```

This could unlock some pretty cool dataloading capabilities and some nice integrations with a simplified inference/analysis API. The big question wrt to some of the problems we've been discussing is which frame should we assume these parameter objects are defined in? We can then provide convenience methods for mapping back and forth depending on what we need, including things like a `from_bilby` classmethod that does some conversion if need be.

**Comment by wbenoit26** [comment]
This is super cool. Definitely gotta take some time to think through everything, but I love the flexibility this introduces.

Given that these objects are primarily being used in the service of generating detector responses, I think the natural assumption to make is that these parameters are in the detector frame.

**Comment by EthanMarx** [comment]
I'll point out pycbcs equivalent [here](https://pycbc.org/pycbc/latest/html/pycbc.inject.html). I think we probably do things better and faster (e.g. vectorized injections, projections, etc.) but worth looking at for inspiration.

**Comment by EthanMarx** [comment]
I'll also add: there are standardized file formats that the CBC pipelines use for defining injections. This is probably a good moment to think about supporting those. I think that would require moving away from `bilby` and to `lalsimualtion` directly. We should talk with Erik and Deep about this
