### ISSUE TITLE
Ensure unwanted keys aren't generated in `BBHPriorDict`s

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/BBHNet#283]
To avoid unwanted default parameter distributions in our priors, we should instantiate our `BBHPriorDict`s with a dictionary of `bilby` priors, rather than creating a default `BBHPriorDict` and overwriting the keys that get populated.

**Comment by wbenoit26** [comment]
@EthanMarx Do you want to address this in #272, or would it be better if I took care of it in a separate PR?

**Comment by EthanMarx** [comment]
@wbenoit26 A separate PR would be great. Can you remind me the benefits of using `BBHPriorDict` over just `PriorDict`?
In the review of that PR, can I suggest we add scatter plots of the `m1` `m2` distributions, as well as maybe redshift for sanity?

**Comment by wbenoit26** [comment]
@EthanMarx The benefits are becoming less pronounced, now that I've found that they're not actually calculating luminosity distance from redshift for us. They still automatically take care of enforcing the constraint on `mass_ratio` - otherwise, we'd have to add a conversion function to tell `bilby` what that constraint means. I think they still simplify things, but I could be convinced otherwise.

For sure, I'll do that.

By the way, not sure if you've seen this already or if it's useful, but it looks like `bilby` does have some functionality for converting to source frame masses: [generate_mass_parameters](https://lscsoft.docs.ligo.org/bilby/api/bilby.gw.conversion.generate_mass_parameters.html#bilby.gw.conversion.generate_mass_parameters)

**Comment by EthanMarx** [comment]
One other thing this PR should add: a `spin_bbh` prior that has waveforms with spin. If we are going to be testing with waveforms that have spin, we should also be training with them

**Comment by wbenoit26** [comment]
Just an equivalent to `nonspin_bbh` but with non-zero priors on `a_i` and `tilt_i`? Yeah, I'll add that.
