### ISSUE TITLE
Constrain chirp mass to ensure consistency with kernel length

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#297]
Given that we only use kernel lengths of 1 second, it probably doesn't make sense to inject events with chirp masses so low that most of their SNR doesn't fall within the kernel. @EthanMarx I believe you have a suggestion as to what a sensible constraint would be

**Comment by EthanMarx** [comment]
Lower bounds on M1 and M2 of 10 will make the maximum signal length  > 32Hz ~ 1.7 seconds. I say we start here.
