### ISSUE TITLE
Build background + injection timeslide catalogues

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#30]
For the test set decided by #27 ,  build a catalogue of timeslides generating ~10s of years worth of background, as well as a mirror catalogue of the same data with signals injected into it.

What is the order of magnitude of the number of injected signals we want in order to generate meaningful ROC curves? Given the length of each injection, how much background data will this require?

**Comment by EthanMarx** [comment]
Yes. Will close now.
