### ISSUE TITLE
Update existing background check

### ISSUE THREAD

**Issue by wbenoit26** [ML4GW/BBHNet#315]
[This](https://github.com/ML4GW/BBHNet/blob/3b26c60492e69dee0284ce72cbd41ce23476e159/projects/sandbox/datagen/datagen/scripts/background.py#L48) check should be updated to reflect the generalization to a single background file.

**Comment by alecgunny** [comment]
Agreed, and we should probably do a check to ensure that the `t0` and duration of the file match whatever expectations were specified as arguments to the function.
