### ISSUE TITLE
Training augmentation: swap one channel of waveforms

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#317]
Before injection, randomly select some subset of the projected waveforms to swap one of their interferometer channels and _not_ get marked as signal. This could help regularize the network to learn that it's not sufficient that there just be a BBH-looking event in each IFO: the events have to have matching templates as well.

**Comment by EthanMarx** [comment]
So swap a single IFO's channel from two kernels with injections so that hanford and livingston have BBH signals with different parameters in them?

**Comment by alecgunny** [comment]
Yeah exactly. I think the only change to how the injection transform gets built is that you would need something like a `p_aug` argument to the class (just what it needs, another parameter) and just divide by this when calculating the new injection probability due to downweighting (since `p_aug` fraction of your injections will end up not being marked as signal, you need to increase the probability of originally selecting samples for injection accordingly)

**Comment by alecgunny** [comment]
Closed by #328
