### ISSUE TITLE
AUROC produces best results when training poorly

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#319]
Because our validation set contains a large amount of low SNR signals that are "hopeless", random guessing actually performs better, since for theses signals below the noise floor, our trained model will label them as background. 

One solution is to perform hopeless SNR rejection on the validation set. The easiest way to implement this would be in the waveform generation project. The training validation split would be performed here. 

The train project would then load in these separately.

**Comment by EthanMarx** [comment]
Was talking with Will on slack: I think the easiest fix is to just rescale the validation waveforms in the train project. I guess the question is the best distribution to scale them to.

**Comment by alecgunny** [comment]
We could just do a floor: map anything beneath the threshold to the threshold (or maybe like a power law starting from the threshold, though you wouldn't want to do it stochastically I guess)

**Comment by wbenoit26** [comment]
What about keeping the distribution the same as we use for training, subject (eventually) to the same annealing process? We'd want to raise the minimum SNR from where it is now, at 1, to something more reasonable, but otherwise, it seems sensible that we should validate on the same distribution that we train on, moving towards a more astrophysical distribution

**Comment by alecgunny** [comment]
No I think in general you want to keep your validation dataset static and representative of your test distribution - it's meant to act as a rough estimate of your test performance (hence why you select on it). You should _want_ to perform worse on the validation set when you haven't been training on waveforms that look like it, and to get better as you start to introduce more representative waveforms. If you did really well at the start, you'd select that model and do poorly at test time.

You don't really care about how good you are on the arbitrary, annealed training distribution, it's just a means to get you to the end you really want, which is to be good on the astrophysical distribution. So it's worth keeping tabs on how much your annealing scheme is moving you towards that goal.

**Comment by EthanMarx** [comment]
I was thinking either the floor method, or bootstrapping from the SNRs greater than the threshold.

**Comment by alecgunny** [comment]
@EthanMarx the SNR flooring is in `main` now, correct? Is this resolved?

**Comment by EthanMarx** [comment]
Yes it is
