### ISSUE TITLE
Link projects together via pinto `pipeline`

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#53]
`pinto` has functionality for executing multiple projects in a sequence from a shared config as a `Pipeline` (a good example from DeepClean is [here](https://github.com/ML4GW/DeepClean/tree/main/projects/sandbox). Might be worth starting to string some of these projects together to kick off a single job (download background, generate waveforms and glitches, train on them), with options to skip data generation if the indicated data files already exist (or with a `force` argument to recreate them even if the _do_ exist).

**Comment by EthanMarx** [comment]
Cool idea. We currently don't have a "generate_background" project, although I can't imagine it being more than a few lines of code. I can put one together.

**Comment by alecgunny** [comment]
That would be awesome. I'm even wondering if it would make sense to move all of the data generation libraries (background, glitches, injections) into the `bbhnet.data` library to more tightly integrate how these tools _write_ data to how the various data loaders _read_ and process that data. Probably out of scope for this particular issue, but could be worth thinking about.
