### ISSUE TITLE
Minimum value for `np.clip` of asds

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#74]
`np.clip` is used [here](https://github.com/ML4GW/BBHNet/blob/main/libs/data/bbhnet/data/waveform_sampler.py#L66) to handle values of 0 from the asd. The minimum value of `1e-6` is non-sensical as all asd values should be smaller than this.

**Comment by EthanMarx** [comment]
@alecgunny If the ASD is producing `0` values, then theres a problem with the data itself. I don't think we should be clipping values, as I am unsure how this effects the whitening. Should we consider raising a value error here, or doing a check in the dataloader to ensure our background data is "pure"

**Comment by alecgunny** [comment]
Hmmm this is actually a super interesting question. Part of me wants to keep the ability to have ASDs with 0 bins for the purposes of exploring toy problems with very specific frequency content, but it also makes operating on real data more complicated. In either case, I 100% agree that the clipping makes no sense at all: if your background has 0 content in a given bin, and a signal has _any_ content there, that should be an infinite SNR.

Would using a `kwarg` to either `__init__` or `fit` that controls whether to raise an error or not be a good middle ground? Something like `allow_zero: bool = False`, that way users who are _very_ confident they want toy behavior can turn it on? If we were to do this, the one question would be how to reweight an infinite SNR? Would we do something in `reweight_snrs` like:

```python
snrs[np.isnan(snr)] = 1
```
So the behavior is to just leave the waveform as-is?

Or I'm also open to the idea of not over complicating things and just raising the error. Thoughts?

**Comment by EthanMarx** [comment]
I think for now we raise the error, and as those sorts of problems arise we implement new features then. 

I can envision scenarios where we play around with signals of specific frequency content. but won't we always want to be using 'real' LIGO background data where there shouldnt be bins with `0` values?

**Comment by alecgunny** [comment]
Yeah you're right, I can imagine _extremely_ artificial problems that might benefit from it but I can't really imagine what use they would be to us, but if that ever changes then you're right we can worry about extensions to this solution then.
