### ISSUE TITLE
update`sample_kernels` 

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#87]
When using the `WhiteningTransform`, we have established that we need to increase the pre-whitening `kernel_length` to account for whitening artifacts at the edge (see this nice visualization [app](https://app.hex.tech/alecgunny/app/2543dfc1-c3fe-423e-abfc-d6f38ad0db2f/latest) Alec built) The WhiteningTransform will then crop `fduration / 2` seconds of data from each end.  One thing to keep in mind is that we want to guarantee that the `t0` of glitches and signals lie within the kernel that the network sees. With the current implementation of [sample_kernels](https://github.com/ML4GW/BBHNet/blob/main/libs/data/bbhnet/data/utils.py#L6), it is possible for the `t0` of signals and glitches to be cropped by the `WhiteningTransform`.

**Comment by EthanMarx** [comment]
Considering the best implementation of this. Maybe an `Optional` parameter `crop_size`  or something that relays the information about how much is being cropped, and is only passed when using the WhiteningTransform.

**Comment by alecgunny** [comment]
`RandomWaveformDataset` could take advantage of such a kwarg with a `trigger_distance` kwarg for itself that defaults to `None`, in which case it gets set to `kernel_length`. So you could set e.g. `kernel_length=3`, but `trigger_distance=1` and replicate the existing functionality with some padding.

**Comment by EthanMarx** [comment]
#90 should address this. 

To clarify, I think the default should be `kernel_length / 2`.  If `t0` is at the last sample of the kernel, the center of the kernel is `kernel_length / 2` seconds away.

To add 1 second of padding on either side of a 1 second kernel, we would use `kernel_length = 3`,  `trigger_distance = 0.5`.

**Comment by alecgunny** [comment]
I guess it's just a question of how you want to define the "distance" involved here. I was thinking of it as the maximum distance (in time) from which _any_ sample of _any_ kernel could fall from the trigger, in which case it would be `kernel_length`. Your definition also makes sense (distance from the trigger time to the center of the kernel).

One thing to note about both of these approaches from an API standpoint is that knowing whether or not a given `trigger_distance` will allow for kernels that don't include the trigger requires _also_ knowing the `kernel_length`. One way to define this in a way that makes them more independent is as the maximum _minimum_ distance that a kernel can fall from the trigger (or the max distance that the edge of the kernel closest to the trigger can be from it). In this case, the default would be 0, and negative values would indicate minimum distance from the edge of the kernel the trigger needs to be, which might also be helpful for our purposes (set it to `-fduration / 2`).

Dealer's choice, but just a couple things to consider.

**Comment by EthanMarx** [comment]
Ah yeah I was running into this issue of determining whether or not the trigger time was in the kernel while writing tests.
It makes sense to me to make them independent. I like the idea of the distance from the end of the kernel to `t0`

**Comment by EthanMarx** [comment]
Also, I assume we're enforcing that the left most edge of the kernel should never go beyond `t0`.
